# Generated by Django 5.2.6 on 2025-09-20 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deu_date', models.DateField()),
                ('deu_time', models.TimeField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='Pending', max_length=10)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('others', 'Others')], max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
